### ISSUE TITLE
Trezor bridge not compatible with firmware

### ISSUE THREAD

**Issue by pun8660** [MangoFarmAssets/RVN-IPFS-Swarm#1]
Hi. I was trying to view my RVN in my wallet but I got a message that the trezor bridge needs to be updated because of the latest firmware. It let me in the wallet but shows a zero balance. Can you please assist me?

**Comment by MangoFarmAssets** [comment]
Hi @pun8660 - of course we will help.  Please email me at info@mangofarmassets.com and I will assist.  I'm going to close this out on github, because it's just a repo for my ipfs swarm files.  Don't worry we will get you sorted.  Regards.

**Comment by pun8660** [comment]
Good morning;                           Thanks for helping me with my issue. I periodically open my mangofarm wallet to view my RVN balance. I went to do it last night and my trezor had a new firmware update. So I updated it. When I started to login a message popped up that the trezor bridge may not be compatible with firmware and contact owner of the wallet. 
Thank you,                     James 

-----Original Message-----

**Comment by MangoFarmAssets** [comment]
OK thanks for bringing this to my attention.  I thought the firmware update was reverse-compatible with the Trezor Bridge.  I'll take a look and report back.

**Comment by MangoFarmAssets** [comment]
Hi, you should be all set now.  You will still get a warning until we upgrade to the new version of Trezor Connect, but the wallet should show your balance now.  We will upgrade in the coming days, but it should not impact functionality as we do not use segwit on RVN.  Thanks again for letting me know.

**Comment by pun8660** [comment]
Thank you. You were correct. I had the message but my balance is in there. I do appreciate it.

-----Original Message-----
